""" config.py 全局配置常量。"""

# ── 视口 ──
VIEW_WIDTH = 40
VIEW_HEIGHT = 18

# ── 世界 ──
WORLD_SEED = 42

# ── 玩家 ──
PLAYER_INITIAL_HP = 100
PLAYER_BASE_DAMAGE_MIN = 2
PLAYER_BASE_DAMAGE_MAX = 5
PLAYER_BASE_HIT_CHANCE = 0.85

# ── 怪物 ──
SPAWN_INITIAL_COUNTDOWN = 20
SPAWN_INTERVAL_MIN = 20
SPAWN_INTERVAL_MAX = 40
SPAWN_MIN_DISTANCE = 10
MONSTER_SLEEP_DISTANCE = 30
MONSTER_SLEEP_TICKS = 5

# ── 昼夜循环 ──
DAY_LENGTH = 1800
DAWN_START = 0
DAY_START = 300
DUSK_START = 1200
NIGHT_START = 1500
